### ISSUE TITLE
压缩成功后返回的formData中没有压缩后的rst.file

### ISSUE THREAD

**Issue by hualebin** [think2011/localResizeIMG#105]
写下以下内容吧（这对判断问题很重要）：

平台：微信|自带浏览器..
设备：iPhone5 IOS7|Android 4.5..
问题：问题描述..

P.S: 问题可能很久才会得到反馈（忙，或者不知道如何回答），但看到一定会考虑，验证的，请放心

**Comment by hualebin** [comment]
好吧其实是有的，不过我后台接收的时候key是file,是默认的还是可以自己设置不是应该读取我表单中设置的name吗

**Comment by think2011** [comment]
因为传入的是file，不是input，所有需要额外指定fieldName参数的。 

https://github.com/think2011/localResizeIMG/wiki/2.-%E5%8F%82%E6%95%B0%E6%96%87%E6%A1%A3
