### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by zbtyx** [think2011/localResizeIMG#110]
写下以下内容吧（这对判断问题很重要）：

平台：微信|自带浏览器..
设备：iPhone5 IOS7|Android 4.5..
问题：
         ** 不能连续上传压缩同一张图片？**
P.S: 问题可能很久才会得到反馈（忙，或者不知道如何回答），但看到一定会考虑，验证的，请放心

**Comment by think2011** [comment]
不太明白，是什么意思呢？
