### ISSUE TITLE
建议添加demo

### ISSUE THREAD

**Issue by yanhaijing** [think2011/localResizeIMG#120]
写下以下内容吧（这对判断问题很重要）：

平台：微信|自带浏览器..
设备：iPhone5 IOS7|Android 4.5..
问题：问题描述..

P.S: 问题可能很久才会得到反馈（忙，或者不知道如何回答），但看到一定会考虑，验证的，请放心

**Comment by think2011** [comment]
https://github.com/think2011/localResizeIMG

demo有的，在二维码那里
