### ISSUE TITLE
谷歌浏览器打开demo报错

### ISSUE THREAD

**Issue by Flyswan** [think2011/localResizeIMG#129]
写下以下内容吧（这对判断问题很重要）：

平台：微信|自带浏览器..
设备：iPhone5 IOS7|Android 4.5..
问题：下载了zip，本地用谷歌浏览器打开index.html直接报错。谷歌浏览器版本 47.0.2526.106 .
额。。截图上传不成功，手动复制浏览器控制台的错误如下：
Image from origin 'file://' has been blocked from loading by Cross-Origin Resource Sharing policy: Invalid response. Origin 'null' is therefore not allowed access.
3lrz.js:78 Uncaught Error: 加载图片文件失败

![Uploading 123.png…]()
![Uploading 123.png…]()

P.S: 问题可能很久才会得到反馈（忙，或者不知道如何回答），但看到一定会考虑，验证的，请放心

**Comment by eyblog** [comment]
看到了顺手回答一下，谷歌浏览器需要放到http服务中打开，因为用了按需加载。。。所有用到ajax的demo谷歌浏览器打开的时候都需要放到http服务中，不能直接打开html文件（ps：这是很基础的问题）
