### ISSUE TITLE
png和gif可否不压缩，直接原始上传以保持透明？

### ISSUE THREAD

**Issue by mrcuncun** [think2011/localResizeIMG#131]
写下以下内容吧（这对判断问题很重要）：

平台：Ubuntu下Chrome
设备：PC
问题：希望上传是png和gif时候可以不压缩成jpg，需要怎么设置或修改？

**Comment by eyblog** [comment]
lrz(file, [options]);

    file 通过 input:file 得到的文件，或者直接传入图片路径

    [options] 这个参数允许忽略

-         width {Number} 图片最大不超过的宽度，默认为原图宽度，高度不设时会适应宽度。
-         height {Number} 同上
-         quality {Number} 图片压缩质量，取值 0 - 1，默认为0.7
-         fieldName {String} 后端接收的字段名，默认：file


quality 设置为1则默认不压缩

**Comment by think2011** [comment]
没有提供设置为其他图片格式的原因是因为只有jpg才有好的压缩率
