### ISSUE TITLE
我是绑定的css ，document.querySelector('.tianj_input')  第二个往下都无效

### ISSUE THREAD

**Issue by Messilimeng** [think2011/localResizeIMG#132]
![image](https://cloud.githubusercontent.com/assets/12272166/17842994/66375804-685b-11e6-9728-0a7d363759c2.png)

每行都要绑定上传图片 但是只有第一个上传 以下的上传都没有反应

**Comment by eyblog** [comment]
不太明白你说的无效是什么意思。能贴代码最好。。。如果是js动态增加的上传按钮，需要使用事件委托。。

**Comment by Messilimeng** [comment]
@eyblog 已经解决了xiexie
