### ISSUE TITLE
使用plupload上传插件时会报Failed to execute 'createObjectURL' on 'URL'

### ISSUE THREAD

**Issue by mylesshie** [think2011/localResizeIMG#133]
写下以下内容吧（这对判断问题很重要）：

平台：chrome
设备：PC

lrz(file, { width: 2048, quality: 1 }).then(rst => {
        console.log('beforeUpload:', file, rst)
        const img = new Image()
        img.src = rst.base64
        img.onload = () => {
          if (img.width / img.height !== 2) {
            message.error('您上传的全景图长宽比例必须是(2:1)')
            reject()
          } else {
            resolve(rst.origin)
          }
        }
      }, () => reject())

报错：Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.(…)

我打印出来的file
```
PluploadFile {id: "o_1arl747fq1ebd161edme15el17ve7", name: "2.jpg", type: "image/jpeg", size: 1606242, origSize: 1606242…}
destroy:destroy()
error:Object
getNative:getNative()
getSource:getSource()
id:"o_1arl747fq1ebd161edme15el17ve7"
lastModifiedDate:Fri Aug 19 2016 03:18:07 GMT+0800 (中国标准时间)
loaded:1048576
name:"2.jpg"
origSize:1606242
percent:70
size:1514268
status:4
type:"image/jpeg


P.S: 问题可能很久才会得到反馈（忙，或者不知道如何回答），但看到一定会考虑，验证的，请放心

**Comment by mylesshie** [comment]
已经解决了，需要传入file.getNative()获取到原生file对象才行，谢谢

**Comment by think2011** [comment]
好噢
