### ISSUE TITLE
安卓比较低的4.n的版本好像会闪退

### ISSUE THREAD

**Issue by chenqi1992** [think2011/localResizeIMG#137]
写下以下内容吧（这对判断问题很重要）：安卓低版本点开图片上传会立即弹回原状态，就是调不出插件函数，目前测试大多数5.0以上没问题

平台：微信|自带浏览器..
设备：vivo Android 4.2..|| 华为 3x play
问题：

P.S: 问题可能很久才会得到反馈（忙，或者不知道如何回答），但看到一定会考虑，验证的，请放心

**Comment by think2011** [comment]
duplicate #85
