### ISSUE TITLE
formData为什么是空的?

### ISSUE THREAD

**Issue by WangShayne** [think2011/localResizeIMG#138]
写下以下内容吧（这对判断问题很重要）：
rst.formData是空的

平台：Chrome 53.0.2785.116 m (64-bit)
设备：windows7
问题：问题描述..
![image](https://cloud.githubusercontent.com/assets/17644818/19506255/893d5780-95fc-11e6-8588-8078a0a6b3d7.png)

**Comment by WangShayne** [comment]
sorry 知道什么原因了,抱歉!

是后端写的接受文件名为uploadFile,formData中默认的是file.

**Comment by forHeyin** [comment]
@WangShayne 遇到了和你一样的问题，不过我是本地上传，还没传到服务器，返回的rst.formData为空，能帮忙解答下么？
