### ISSUE TITLE
新版插件无法多次上传同一张图片

### ISSUE THREAD

**Issue by yanhan569046480** [think2011/localResizeIMG#141]
文件表单默认的change响应可以多次上传同一张图片，还有微信发朋友圈也可以的，旧版的插件也可以上传同一张图片，但是新版无法做到，当连续传同一张图片的时候，第二次会没有反应，不管合不合理，这种需求是存在的，希望听听作者的看法

**Comment by LiruiBryant** [comment]
我也遇到了这种情况，有解决办法了吗

**Comment by newShen119** [comment]
我也遇到了

**Comment by supersheep09** [comment]
临时解决办法，每次上传完，把FILE控件的VALUE清空一下

**Comment by moxiaonai** [comment]
我也在项目中遇到了，找到了这里，去试试楼上的方法清空file的value，待会再来回复结果

**Comment by moxiaonai** [comment]
测试了，清空file的value可以解决
![image](https://cloud.githubusercontent.com/assets/13172934/21263110/daf92e90-c3cf-11e6-9db3-ca799fd6fce4.png) it's so cool
