### ISSUE TITLE
“当压缩后的体积比压缩前大，会发送原图”的疑问

### ISSUE THREAD

**Issue by nottellyou** [think2011/localResizeIMG#142]
平台：webview
设备：android 4.4及以上
问题1：
有这样一种情况，安桌webview加载一h5页面，有一上传图片功能，发现在android4.3上正常，到了android4.4上面，上传图片时，不发送文件后缀名，导致上传失败。我也搞不懂什么情况，干脆来了一个粗暴的方法：移动端直接base64上传。选择文件后就上传，没有预览。

现在看到这个JS库，问下“当压缩后的体积比压缩前大，会发送原图”，这是发送的base64方式还是传统的方式？？？？

问题2：如果能将原始文件名也传过来就更好了，这里好像有
https://github.com/think2011/localResizeIMG/issues/95

**Comment by think2011** [comment]
> “当压缩后的体积比压缩前大，会发送原图” 是以传统方式传的，base64要大源文件的30%左右，所以压缩率不高不如发源文件了
