### ISSUE TITLE
大神，安卓4.4.2 & 微信中，拍照上传页面会刷新，怎么破呢？test也是咯

### ISSUE THREAD

**Issue by OXOYO** [think2011/localResizeIMG#19]
1G的内存，拍照上传直接刷新页面了。

不知道有没有判断禁用拍照，改用选择图片是不是会好些？

**Comment by think2011** [comment]
Duplicate of #18  

关于闪退，找个时间试试看能不能解决吧，但不是很有信心。

另外可以试试 `<input type="file" accept="image/*" />` demo已换成这样的例子了。
这里有一份说明和测试例子，可以去试试 http://www.wufoo.com/html5/attributes/20-accept.html

**Comment by OXOYO** [comment]
好嘛，谢谢了。时刻关注。

**Comment by francisfeng** [comment]
这个貌似是因为 Android 的 bug，只存在于特定的版本。

查看：
https://code.google.com/p/android/issues/detail?id=62220
http://segmentfault.com/q/1010000001581416

**Comment by think2011** [comment]
@francisfeng 恩，是的，

关于无法响应input:file问题随着时间会过去的。 
关于闪退，我能没在网上找到有效的资料，打算找个时间重现一下，然后逐行调试，期望不是系统级的问题。

**Comment by kenberkeley** [comment]
作者大大，我把你最后这个坑也踩了。。。  
主要是拍照直传（选择文件上传还没遇到过），input中accept="image/*"。  
  
这是偶发性事件，只有在特定情况下进行拍照直传才会导致刷新。  
但是这个“特定情况”是什么，倒不是很清楚。。。

**Comment by kenberkeley** [comment]
我擦。。。今天测试的时候，把“闪退”这个坑也踩了。。。  
昨天我提到的“特定情况”，我分析了一下，应该是**内存不足**。  
  
也就是说，闪退也好，刷新也罢，很有可能都是由于页面占用内存过多，  
出于浏览器对自身的保护也好，优化也罢，反正就是会采取强有力的释放内存的行为。

**Comment by think2011** [comment]
@kenberkeley 

怀疑也是这种原因，理论上来说会闪退的设备应该是足够内存处理的，或者说是浏览器提供给这方面处理的内存有限制。

那.. 还是无解..

**Comment by BlueTT** [comment]
我这里也确实出现了这个问题。但是我看了discuz的程序，他就没问题，能正常用。不知道他是做了什么处理，网上说是内存不足引起的。请问现在解决了吗？

**Comment by think2011** [comment]
@BlueTT 在哪里可以看到discuz地址呢？ 我想去看看。

**Comment by BlueTT** [comment]
@think2011   就discuz的官网，www.discuz.net 用移动设备打开，登录后，发帖就可以看到了，有结果了麻烦告诉我一下，谢谢！

**Comment by think2011** [comment]
@BlueTT 恩，会的。

**Comment by think2011** [comment]
@BlueTT 调试一下源码，注意到每次只上传一张图片之外似乎没什么太大的不同（也有可能我没有弄明白）

由于我身边的设备（包括模拟器）都没法重现这个问题，现在不知道如何去解决。

**Comment by BlueTT** [comment]
@think2011  我这边有台设备可以测试，确实会出现这个问题，但是具体怎么解决。

varjq=jQuery.noConflict();var$=jq;varfid=TOOLS.getQuery("fid");SITE_ID=TOOLS.getQuery("siteId")==null?SITE_ID: TOOLS.getQuery("siteId");uid=TOOLS.getQuery("uid");fid=TOOLS.getQuery("fid");formhash=TOOLS.getQuery("formhash");forumname=TOOLS.getQuery("forumname");uploadHash="";threadtypes=null;threadtypeHtml="";uploadImage=false;JC.load("../cdn/"+JS_DIR+"/js/secure.js",
null,
JC.BODY);varnewThread={
    maxUpload: 8,
    uploadInfo: {
        
    },
    uploadQueue: [
        
    ],
    previewQueue: [
        
    ],
    xhr: {
        
    },
    isBusy: false,
    userName: "",
    fid: 0,
    touchEnd: function(a,
    b){
        document.ontouchmove=function(c){
            returntrue
        }
    },
    countUpload: function(){
        vara=0;jq.each(newThread.uploadInfo,
        function(b,
        c){
            if(c){
                ++a
            }
        });returna
    },
    getbuilder: function(d,
    b,
    e,
    h){
        varf="--",
        g="\r\n",
        a="";for(varcind.uploadformdata){
            a+=f;a+=h;a+=g;a+='Content-Disposition: form-data;name="'+c+'"';a+=g;a+=g;a+=d.uploadformdata[
                c
            ];a+=g
        }a+=f;a+=h;a+=g;a+='Content-Disposition: form-data;name="'+d.uploadinputname+'"';a+=';filename="'+b+'"';a+=g;a+="Content-Type: application/octet-stream";a+=g;a+=g;a+=e;a+=g;a+=f;a+=h;a+=f;a+=g;returna
    },
    uploadPreview: function(e){
        varb=newFileReader();vara;varc={
            
        },
        d=newThread.uploadInfo[
            e
        ].file;b.onload=function(i){
            varf=this.result;if(d.type=="image/jpeg"){
                varh=newJpegMeta.JpegFile(f,
                d.name);if(h.tiff&&h.tiff.Orientation){
                    c=jq.extend(c,
                    {
                        orien: h.tiff.Orientation.value
                    })
                }
            }if(ImageCompresser.support()){
                varg=newImage();g.onload=function(){
                    try{
                        a=ImageCompresser.getImageBase64(this,
                        c)
                    }catch(j){
                        TOOLS.dialog({
                            content: "压缩图片失败",
                            autoClose: true
                        });jq("#li"+e).remove();returnfalse
                    }if(a.indexOf("data:image")<0){
                        TOOLS.dialog({
                            content: "上传照片格式不支持",
                            autoClose: true
                        });jq("#li"+e).remove();returnfalse
                    }newThread.uploadInfo[
                        e
                    ].file=a;newThread.uploadInfo[
                        e
                    ].filename=d.name;jq("#li"+e).find("img").attr("src",
                    a);newThread.uploadQueue.push(e)
                };g.src=ImageCompresser.getFileObjectURL(d)
            }else{
                a=f;if(a.indexOf("data:image")<0){
                    TOOLS.dialog({
                        content: "上传照片格式不支持",
                        autoClose: true
                    });jq("#li"+e).remove();returnfalse
                }newThread.uploadInfo[
                    e
                ].file=a;newThread.uploadInfo[
                    e
                ].filename=d.name;jq("#li"+e).find("img").attr("src",
                a);newThread.uploadQueue.push(e)
            }
        };b.readAsBinaryString(newThread.uploadInfo[
            e
        ].file)
    },
    _keys: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
    base64decode: function(d){
        varb="";varl,
        j,
        g="";vark,
        h,
        f,
        e="";varc=0;if(d.length%4!=0){
            return""
        }vara=/[
            ^A-Za-z0-9\+\/\=
        ]/g;if(a.exec(d)){
            return""
        }do{
            k=newThread._keys.indexOf(d.charAt(c++));h=newThread._keys.indexOf(d.charAt(c++));f=newThread._keys.indexOf(d.charAt(c++));e=newThread._keys.indexOf(d.charAt(c++));l=(k<<2)|(h>>4);j=((h&15)<<4)|(f>>2);g=((f&3)<<6)|e;b=b+String.fromCharCode(l);if(f!=64){
                b+=String.fromCharCode(j)
            }if(e!=64){
                b+=String.fromCharCode(g)
            }l=j=g="";k=h=f=e=""
        }while(c<d.length);returnb
    },
    createUpload: function(b){
        if(!newThread.uploadInfo[
            b
        ]){
            returnfalse
        }vark=API_URL+"siteid="+SITE_ID+"&version=4&module=forumupload&fid="+fid+"&type=image&simple=1";varm='<divclass="progress"id="progress'+b+'"><divclass="proBar"style="width:0%;"></div></div>';jq("#li"+b).find(".maskLay").after(m);vare=newFormData();e.append("Filedata",
        newThread.uploadInfo[
            b
        ].file);e.append("uid",
        uid);e.append("hash",
        uploadHash);vara=function(r){
            if(r.target.response){
                varo=jq.parseJSON(r.target.response);if(o.errCode!=0){
                    TOOLS.dialog({
                        content: "网络不稳定，请稍后重新操作",
                        autoClose: true
                    });f(b)
                }
            }varp=jq("#progress"+b).find(".proBar");if(r.total==r.loaded){
                varq=100
            }else{
                varq=100*(r.loaded/r.total)
            }if(q>100){
                q=100
            }p.css("width",
            q+"%");if(q==100){
                jq("#li"+b).find(".maskLay").remove();jq("#li"+b).find(".progress").remove()
            }
        };varf=function(o){
            l(o);jq("#li"+o).remove()
        };varl=function(p){
            newThread.isBusy=false;newThread.uploadInfo[
                p
            ].isDone=true;newThread.xhr[
                p
            ]=null;varo={
                a: "upload",
                uid: uid||""
            };TOOLS.addReportCount(o)
        };varc=function(q){
            l(b);varp=q.target.response.split("|");if(p.length>3&&parseInt(p[
                2
            ])>0){
                varo='<inputtype="hidden"id="attachnew'+b+'"name="attachnew['+p[2]+'][description]"value="'+p[2]+'">';jq("#newthread").append(o);jq("#li"+b).find(".maskLay").remove();jq("#li"+b).find(".progress").remove()
            }else{
                if(parseInt(p[
                    1
                ])==3){
                    TOOLS.dialog({
                        content: "图片过大, 应小于 "+p[
                            4
                        ]/1024+" KB",
                        autoClose: true
                    })
                }else{
                    TOOLS.dialog({
                        content: "网络不稳定，请稍后重新操作",
                        autoClose: true
                    })
                }f(b)
            }
        };varh=function(){
            newThread.isBusy=false;newThread.uploadInfo[
                b
            ].isDone=true;TOOLS.dialog({
                content: "网络断开，请稍后重新操作",
                autoClose: true
            });f(b)
        };varg=function(){
            newThread.isBusy=false;newThread.uploadInfo[
                b
            ].isDone=true;TOOLS.dialog({
                content: "上传已取消",
                autoClose: true
            });f(b)
        };newThread.xhr[
            b
        ]=newXMLHttpRequest();vard="------multipartformboundary"+(newDate).getTime();varn={
            uploadformdata: {
                uid: uid,
                hash: uploadHash
            },
            uploadinputname: "Filedata"
        };varj=newThread.uploadInfo[
            b
        ].file.replace(/data: .+;base64,
        /,
        "");if(typeofatob=="function"){
            j=atob(j)
        }else{
            j=newThread.base64decode(j)
        }vari=newThread.getbuilder(n,
        newThread.uploadInfo[
            b
        ].filename,
        j,
        d);newThread.xhr[
            b
        ].open("POST",
        k,
        true);newThread.xhr[
            b
        ].setRequestHeader("content-type",
        "multipart/form-data; boundary="+d);if(!XMLHttpRequest.prototype.sendAsBinary){
            XMLHttpRequest.prototype.sendAsBinary=function(p){
                functionq(s){
                    returns.charCodeAt(0)&255
                }varr=Array.prototype.map.call(p,
                q);varo=newUint8Array(r);this.send(o.buffer)
            }
        }newThread.xhr[
            b
        ].sendAsBinary(i);newThread.xhr[
            b
        ].onerror=function(o){
            h()
        };newThread.xhr[
            b
        ].onload=function(o){
            c(o)
        };newThread.xhr[
            b
        ].abort=function(o){
            g()
        };newThread.xhr[
            b
        ].onsendstream=function(o){
            a(o)
        }
    },
    initUpload: function(){
        if(uploadImage){
            TOOLS.uploadCompatible("#addPic",
            "#uploadnotice");jq("#addPic").on("click",
            function(){
                if(!newThread.isBusy){
                    jq("#uploadFile").click()
                }else{
                    TOOLS.dialog({
                        content: "图片上传中，请稍后添加",
                        autoClose: true
                    });returnfalse
                }
            })
        }else{
            jq("#addPic").on("click",
            function(){
                TOOLS.dialog({
                    content: "当前版块不支持图片上传",
                    autoClose: true
                })
            });jq("#uploadnotice").html("当前版块不支持图片上传")
        }jq(".warp").on("change",
        "#uploadFile",
        function(f){
            f=f||window.event;vara=f.target.files;if(!a.length){
                returnfalse
            }for(vard=0;d<a.length;d++){
                if(newThread.countUpload()>=newThread.maxUpload){
                    TOOLS.dialog({
                        content: "你最多只能上传8张照片",
                        autoClose: true
                    });break
                }varc=a[
                    d
                ];if(!newThread.checkPicSize(c)){
                    TOOLS.dialog({
                        content: "图片体积过大",
                        autoClose: true
                    });continue
                }if(!newThread.checkPicType(c)){
                    TOOLS.dialog({
                        content: "上传照片格式不支持",
                        autoClose: true
                    });continue
                }varg=Date.now()+d;newThread.uploadInfo[
                    g
                ]={
                    file: c,
                    filename: "",
                    isDone: false
                };varb='<liid="li'+g+'"><divclass="photoCut"><imgsrc="cdn/'+JS_DIR+'/images/defaultImg.jpg"class="attchImg"alt="photo"></div><divclass="maskLay"></div><ahref="javascript:;"class="cBtn cBtnOn pa db"title=""_id="'+g+'">关闭</a></li>';jq("#addPic").before(b);newThread.previewQueue.push(g)
            }if(newThread.countUpload()>=newThread.maxUpload){
                jq("#addPic").hide()
            }jq(this).val("")
        });jq(".photoList").on("click",
        ".cBtn",
        function(){
            vara=jq(this).attr("_id");if(newThread.xhr[
                a
            ]){
                newThread.xhr[
                    a
                ].abort()
            }jq("#li"+a).remove();jq("#input"+a).remove();jq("#attachnew"+a).remove();newThread.uploadInfo[
                a
            ]=null;if(newThread.countUpload()<newThread.maxUpload){
                jq("#addPic").show()
            }
        });setInterval(function(){
            setTimeout(function(){
                if(newThread.previewQueue.length){
                    vara=newThread.previewQueue.shift();newThread.uploadPreview(a)
                }
            },
            1);setTimeout(function(){
                if(!newThread.isBusy&&newThread.uploadQueue.length){
                    vara=newThread.uploadQueue.shift();newThread.isBusy=true;newThread.createUpload(a)
                }
            },
            10)
        },
        300)
    },
    init: function(){
        newThread.fid=TOOLS.getQuery("fid");jQuery("#subject").focus();TOOLS.getCheckInfo(function(d){
            
        });TOOLS.initTouch({
            obj: jq(".warp")[
                0
            ],
            end: newThread.touchEnd
        });varc={
            dataType: "json",
            success: function(d){
                if(parseInt(d.Version)==1&&parseInt(d.Variables.allowperm.allowpost)==1){
                    formhash=d.Variables.formhash;jq("#formhash").val(formhash);uid=d.Variables.member_uid;uploadHash=d.Variables.allowperm.uploadhash;if(d.Variables.allowperm.allowupload){
                        jq.each(d.Variables.allowperm.allowupload,
                        function(g,
                        h){
                            if(g.indexOf("jpg")!=-1||g.indexOf("jpeg")!=-1||g.indexOf("gif")!=-1||g.indexOf("png")!=-1){
                                if(parseInt(h)==-1||parseInt(h)>0){
                                    uploadImage=true
                                }
                            }
                        })
                    }else{
                        uploadImage=false
                    }newThread.initForm();vare={
                        dataType: "json",
                        success: function(h){
                            TOOLS.hideLoading();if(parseInt(h.Version)==1){
                                for(varginh.Variables.forums){
                                    if(parseInt(h.Variables.forums[
                                        g
                                    ].fid)==parseInt(fid)){
                                        threadtypes=h.Variables.forums[
                                            g
                                        ].threadtypes;forumname=h.Variables.forums[
                                            g
                                        ].name;jq("#forumname").html("所在版块："+(forumname?forumname: ""));break
                                    }
                                }if(threadtypes&&typeofthreadtypes.required!="undefined"){
                                    jq.each(threadtypes.types,
                                    function(i,
                                    j){
                                        j=TOOLS.stripCode(j);threadtypeHtml+='<aclass="f12"key="'+i+'">'+j+"</a>&nbsp;"
                                    });jq("#span_typeid .customTag").html(threadtypeHtml);jq("#span_typeid .customTag a").on("click",
                                    function(i){
                                        jq("#typeid").val(jq(this).attr("key"));jq("#span_typeid .customTag a").removeClass("on");jq(this).addClass("on")
                                    });jq("#span_typeid").show()
                                }newThread.userName=d.Variables.member_username
                            }
                        }
                    };TOOLS.dget(API_URL+"siteid="+SITE_ID+"&module=forumnav&version=1",
                    null,
                    e.success,
                    function(g){
                        TOOLS.hideLoading();TOOLS.showTips(g.messagestr,
                        true)
                    });varf=TOOLS.hook(d,
                    "newthread_extraInfo");f=TOOLS.stripCode(f);jq("#customHtml").append(f)
                }else{
                    TOOLS.dialog({
                        isMask: true,
                        content: "当前账户暂无发帖权限",
                        isShowMask: true,
                        cancelValue: "确定",
                        cancel: function(){
                            newThread.goBack()
                        }
                    })
                }
            }
        };jq("#newthread").attr("action",
        API_URL+"siteid="+SITE_ID+"&version=4&module=newthread&fid="+fid+"&topicsubmit=yes");varb=API_URL+"siteid="+SITE_ID+"&module=newthread&fid="+fid+"&submodule=checkpost&version=1";TOOLS.showLoading();TOOLS.dget(b,
        null,
        c.success,
        function(d){
            TOOLS.hideLoading();TOOLS.showTips(d.messagestr,
            true);jq("#submitButton").bind("click",
            function(){
                TOOLS.showTips("无法发送,请取消并检查网络后重进",
                true);returnfalse
            });jq(".cancelBtn").bind("click",
            function(){
                newThread.goBack()
            })
        });emotion.init();jQuery(".expreSelect").click(function(){
            emotion.show();jQuery(".photoList").hide()
        });jQuery(".photoSelect").click(function(){
            emotion.hide();jQuery(".photoList").show()
        });jQuery(".backBtn").click(function(){
            TOOLS.openNewPage("?c=index&a=index&f="+F+"&fid="+newThread.fid+"&siteid="+SITE_ID)
        });secure.checkDzVersion();document.addEventListener("WeixinJSBridgeReady",
        functiona(){
            WeixinJSBridge.call("hideOptionMenu")
        })
    },
    sendPost: function(c,
    a){
        c=c||"";a=a||"";varb={
            success: function(f){
                varg=f.Message.messageval;TOOLS.hideLoading();TOOLS.showTips("发帖成功",
                true);jq("#submitButton").disabled=false;clearInterval(timer);localStorage.removeItem(newThread.storageContentKey);localStorage.removeItem(newThread.storageSubjectKey);vare={
                    a: "newthread",
                    uid: uid||"",
                    tid: f.Variables.tid
                };TOOLS.addReportCount(e);setTimeout(function(){
                    TOOLS.openNewPage("?c=index&a=viewthread&f="+F+"&tid="+f.Variables.tid+"&siteid="+SITE_ID)
                },
                300)
            }
        };vard=jq("#newthread").attr("action")+c;TOOLS.dpost(d,
        jq("#newthread").serialize()+a,
        b.success,
        function(e){
            TOOLS.hideLoading();if(e.messageval=="post_sort_isnull"){
                TOOLS.showTips("手机上暂不支持发表分类信息，请移步PC进行操作",
                true);return
            }if(e.messageval=="submit_seccode_invalid"){
                secure.isChecked=false;newThread.checkSecure(1)
            }else{
                TOOLS.showTips(e.messagestr,
                true)
            }jq("#submitButton").disabled=false
        });jq("#submitButton").disabled=true;TOOLS.showLoading(null,
        "正在发帖中...",
        false)
    },
    checkSecure: function(a){
        secure.checkSecure({
            success: function(){
                if(secure.isNeedSecure){
                    varb={
                        seccode: secure.seccode,
                        secqaa: secure.secqaa,
                        success: function(c){
                            vard="&sechash="+secure.sechash+"&seccodeverify="+c.seccodeverify+"&secanswer="+c.secanswer;newThread.sendPost("",
                            d)
                        }
                    };secure.showSecure(b);returnfalse
                }else{
                    newThread.sendPost("",
                    "")
                }
            },
            error: function(b){
                
            }
        },
        "post",
        a)
    },
    initForm: function(){
        newThread.storageContentKey=uid+"thread_content";newThread.storageSubjectKey=uid+"thread_subject";jq("#message").val(localStorage.getItem(newThread.storageContentKey));jq("#subject").val(localStorage.getItem(newThread.storageSubjectKey));timer=setInterval(function(){
            if(TOOLS.mb_strlen(jq('textarea[
                name="message"
            ]').val())>500*2){
                jq('textarea[
                    name="message"
                ]').val(jq('textarea[
                    name="message"
                ]').val().substring(0,
                500*2))
            }TOOLS.strLenCalc(jq('textarea[
                name="message"
            ]')[
                0
            ],
            "pText",
            500*2);if(jq('textarea[
                name="message"
            ]').val()||jq("#subject").val()){
                localStorage.removeItem(newThread.storageContentKey);localStorage.setItem(newThread.storageContentKey,
                jq("#message").val());localStorage.removeItem(newThread.storageSubjectKey);localStorage.setItem(newThread.storageSubjectKey,
                jq("#subject").val())
            }
        },
        500);jq("#submitButton").bind("click",
        function(){
            if(!newThread.checkForm()){
                returnfalse
            }if(newThread.countUpload()){
                jq("#allowphoto").val(1)
            }vara=OS.toLowerCase();jQuery('input[
                name="mobiletype"
            ]').val(5);newThread.checkSecure();returnfalse
        });jq(".cancelBtn").bind("click",
        function(){
            if(jq(".photoList .attchImg").length>0){
                vara=confirm("是否放弃当前内容?")
            }else{
                vara=true
            }if(a){
                clearInterval(timer);newThread.goBack()
            }
        });newThread.initUpload();newThread.initModal()
    },
    initModal: function(){
        jq("#submitButton").bind("touchstart",
        function(){
            jq(this).addClass("sendOn")
        }).bind("touchend",
        function(){
            jq(this).removeClass("sendOn")
        });jq("#cBtn").bind("touchstart",
        function(){
            jq(this).addClass("cancelOn")
        }).bind("touchend",
        function(){
            jq(this).removeClass("cancelOn")
        })
    },
    checkForm: function(){
        jq.each(newThread.uploadInfo,
        function(b,
        c){
            if(c&&!c.isDone){
                TOOLS.dialog({
                    content: "图片上传中，请等待",
                    autoClose: true
                });returnfalse
            }
        });vara=TOOLS.mb_strlen(TOOLS.trim(jq("#subject").val()));if(a<1){
            TOOLS.dialog({
                content: "请输入标题",
                autoClose: true
            });returnfalse
        }a=TOOLS.mb_strlen(TOOLS.trim(jq("#message").val()));if(a<15){
            TOOLS.dialog({
                content: "内容过短",
                autoClose: true
            });returnfalse
        }if(threadtypes&&parseInt(threadtypes.required)==1&&jq("#typeid").val()=="0"){
            TOOLS.dialog({
                content: "请选择主题分类",
                autoClose: true
            });returnfalse
        }returntrue
    },
    checkPicSize: function(a){
        if(a.size>10000000){
            returnfalse
        }returntrue
    },
    checkPicType: function(b){
        if(b.type.indexOf("image/")==0){
            returntrue
        }else{
            vara=b.name.lastIndexOf(".");varc=b.name.substring(a+1).toLowerCase();if(c=="jpg"||c=="jpeg"||c=="png"||c=="gif"){
                returntrue
            }returnfalse
        }
    },
    goBack: function(){
        TOOLS.openNewPage("?c=index&a=index&f="+F+"&fid="+newThread.fid+"&siteid="+SITE_ID)
    }
};newThread.init();window.onload=function(){
    vara=document.getElementById("submitButton");a.ontouchstart=function(){
        this.className="sendBtn sendOn c1 db"
    };a.ontouchend=function(){
        this.className="sendBtn c1 db"
    }
};

**Comment by think2011** [comment]
@BlueTT  最新提交的版本尝试解决了一下，有空请帮忙看看是否解决了问题。

**Comment by BlueTT** [comment]
@think2011  好的我试试！

**Comment by wangjunhua0824** [comment]
oppo型号X9077，安卓4.3，微信浏览器，使用4.8.35，最新压缩代码，闪退严重，即使本地上传也会闪退，是不是优化代码有问题？

**Comment by xujun1986** [comment]
+1

**Comment by lingerdu** [comment]
+1

**Comment by think2011** [comment]
+1

**Comment by think2011** [comment]
有网友测试过， [discuz](http://wsq.discuz.qq.com/?siteid=247742674&source=wap&c=index&a=index&mobile=2) 以及 腾讯部落也存在同样的问题，似乎还在无解..
