### ISSUE TITLE
图片变大了、、、、

### ISSUE THREAD

**Issue by yuu2lee4** [think2011/localResizeIMG#33]
传了一张jpg的430宽的图片 然后参数是width：640 qulity：1  传到服务器后  大小还是430  这是对的 但是图片由20多kb变成了80多kb。。。。

**Comment by yuu2lee4** [comment]
我们这边的要求应该是压缩后保持体积在20kb以内。。现在看来没法精确控制

**Comment by kenberkeley** [comment]
试试把**quality**设置低一点。。。  
我的话，1M内一般都是0.3，大于1M就0.2，压缩率都在90%左右。  
  
当然了，最好设置一个判断，小于50KB的就直接用File API上传，不压缩，不然有可能面目全非。。。

**Comment by yuu2lee4** [comment]
嗯 小于20的直接上传。。。大于的 如果有个压缩后的大小参数就好了。。。

**Comment by kenberkeley** [comment]
压缩后的大小文档有提到，就是re.base64Len。
```
    ...
    .then(function(re) {
        console.log(re); // 详细请看控制台
    })
    ...
```

**Comment by yuu2lee4** [comment]
为什么qulity设置为1  那不就是不压缩么 怎么还变大了呢  我说的压缩参数 是调用lyz的时候传入你想要压缩后的一个大小  优先级是 width >size>qulity  优先缩放width  然后在按size缩小或者qulity压缩，size和qulity同时传入的时候只执行size

**Comment by kenberkeley** [comment]
呃。。。实际上范围只有0~1，因此1显然不是*不压缩*。。。  
所谓的**变大了**，这就涉及到base64编码的问题了。请参考 http://blog.csdn.net/sallay/article/details/3550740

**Comment by yuu2lee4** [comment]
转换成base64变大 base64转换回图片格式 不会变回来么？

**Comment by kenberkeley** [comment]
这就要看作者大大具体的压缩实现了

**Comment by think2011** [comment]
@yuu2lee4 终于理解你在 #32 说的内容了... @kenberkeley 说的没错，base64如果小的话，得不偿失。

现在想到方向有3点：

1. 想办法接上File API接口，以File API接口为主，base64为辅（或者直接取消掉）。
2. 那么文件小的话，就直接走File API接口，文件大就先base64，再走File API。
3. File API 还有进度事件可以检测。

这样变动会很大，找个时间好好研究一下。

**Comment by jerry-he** [comment]
@think2011     不知道这样可行不？判断base64后大小，选择合适的上传，貌似和你说的接上formdata接口一个意思，不知道这个想办法接上是指？

**Comment by think2011** [comment]
@jerry-he 是的，跟你说的一样。

Duplicate #32

**Comment by think2011** [comment]
已更新版本，API和处理均有变动，请务必阅读wiki。

**Comment by yuu2lee4** [comment]
哦  给个赞  看了一下api  还是不能设定压缩后的具体值么

**Comment by think2011** [comment]
想了一下，似乎没办法实现压缩到具体值，大小不是根据尺寸，而是色彩等综合决定的。

发自我的 iPhone

**Comment by think2011** [comment]
想了一下，似乎没办法实现压缩到具体值，大小不是根据尺寸，而是色彩等综合决定的。

**Comment by yuu2lee4** [comment]
不是qulity决定压缩后的大小么。。。那么根据压缩后的大小不就能反推qulity了么

**Comment by think2011** [comment]
不是的，你可以找几张各不同的照片，用Photoshop手动模拟一下结果。

发自我的 iPhone

**Comment by yuu2lee4** [comment]
哦  明白了  细想下来 确实做不到 不知道后端压缩是什么机制
