### ISSUE TITLE
还是不行哦  再看看

### ISSUE THREAD

**Issue by Messilimeng** [think2011/localResizeIMG#35]
![7476c310-7611-11e5-9192-e728fb5432c3](https://cloud.githubusercontent.com/assets/12272166/10569179/cba5e81c-7654-11e5-8be6-ab45ae6721d8.png)

**Comment by Messilimeng** [comment]
还是ios 6

**Comment by think2011** [comment]
将有问题的照片【原件】发到我的邮箱 452125301.hzplay@gmail.com 吧，需要调试一下。

再告知我一下设备的型号和系统版本。

**Comment by Messilimeng** [comment]
@think2011 你这是系统自动回复？

**Comment by think2011** [comment]
@Messilimeng 不是噢.. 我没有原件我没法测试..

**Comment by Messilimeng** [comment]
你没有ios 6 系统 你怎么测试啊  图片不都是一样的吗

**Comment by think2011** [comment]
可以用虚拟机，照片得是从实际上拍摄的原件。

其他就说来话长了，你得去看看源码，并不是很复杂。

**Comment by Messilimeng** [comment]
等我闲下来再看源码吧 。产品马上上线了  不知道是不是 只有ios 6 才会出现着问题  其他手机我发现还是很好的  。 如果可以的话 麻烦你能不能尽早解决呢？

**Comment by think2011** [comment]
我还没有收到图片噢，没有图片我没法测试..

**Comment by Messilimeng** [comment]
你qq 给我 我发给你

**Comment by Messilimeng** [comment]
![qq 20151020091642](https://cloud.githubusercontent.com/assets/12272166/10595490/49c0530c-770b-11e5-87c2-92c10f68e09c.jpg)

**Comment by think2011** [comment]
已更新版本，API和处理均有变动，请务必阅读wiki。
