### ISSUE TITLE
处理旋转图片时的一点点不知道是不是问题的问题

### ISSUE THREAD

**Issue by richard-chen-1985** [think2011/localResizeIMG#39]
在处理旋转图像时，在OPTIONS里给定的width和height参数，在_getResize方法中被互换了，于是有了如下效果：

想得到一个{width: 500, height: 400}的图，实际上确得到了{width: 400, height: 500}的图。不知道这是作者故意为之，还是算是一个bug呢？

影响代码位于lrz.js的https://github.com/think2011/localResizeIMG4/blob/master/src/lrz.js#L245

**Comment by think2011** [comment]
已更新版本，API和处理均有变动，请务必阅读wiki。
