### ISSUE TITLE
31号新版本 安卓5.1系统无反应

### ISSUE THREAD

**Issue by xiaoily520** [think2011/localResizeIMG#41]
平台：手机浏览器 如QQ浏览器
设备：安卓5.1 荣耀4c
问题：31号新版本 安卓5.1系统无反应 用16号旧版本可以，31号的版本用低版本的安卓手机可以上传，打包网址在app也可以用新版

**Comment by xiaoily520** [comment]
电脑上浏览器模拟手机也可以的

**Comment by richard-chen-1985** [comment]
新版在小米4C的UC浏览器也不能用，可能是个兼容性问题

**Comment by think2011** [comment]
http://think2011.github.io/localResizeIMG/test/

用在线demo测试会出现出错提示吗？ 

最新版本新加了Blob特性，根据文档来看符合兼容的，具体我还是测试一下。

**Comment by xiaoily520** [comment]
手机浏览器 在线测试地址也没反应

**Comment by think2011** [comment]
我用android 5.1的自带浏览器没能重新问题（暂时没安装QQ浏览器之类的测试），或许又是奇怪的各机型各浏览器实现的兼容性问题..

**Comment by xiaoily520** [comment]
我手机自带的浏览器貌似也是QQ内核的，没办法，用lrz.all.bundle.js也不可以

**Comment by think2011** [comment]
http://bbs.mb.qq.com/thread-269889-1-1.html

看到有人提QQ浏览器关于Blob的问题。

**Comment by think2011** [comment]
找到有解决方案了，晚点处理一下。

**Comment by xiaoily520** [comment]
恩，作者真是神速啊

**Comment by think2011** [comment]
还好有前人踩过的坑。

目测解决了问题，直接用在线demo试试吧。

**Comment by xiaoily520** [comment]
测试可以了
