### ISSUE TITLE
关于图片旋转还是存在的一点问题

### ISSUE THREAD

**Issue by richard-chen-1985** [think2011/localResizeIMG#42]
目前最新版中，发现某些旋转图片会被拉伸，问题依然存在于getSize方法中，需要增加一个宽高转换，比如在https://github.com/think2011/localResizeIMG/blob/master/src/lrz.js#L264 处，插入如下代码：
```js
if("5678".indexOf(orientation) > -1) {
  ret.width = img.height;
  ret.height = img.width;
}
```
亲测有效，之前的代码在iphone4s及某些安卓上都会出现拉伸情况

**Comment by think2011** [comment]
之前犹豫了一下，删除了这段代码。

能否发有问题的照片原件到我的邮箱（452125301.hzplay@gmail.com），我测试一下呢？

P.S：在http://think2011.github.io/localResizeIMG/test/中的4张需要旋转的方向图没有问题，不知道会不会是某些特定设备的原因，顺便告知我一下设备的型号和系统吧，谢谢！

**Comment by richard-chen-1985** [comment]
一大早来就在忙，这个问题无论在手机拍照还是选择照片都会出现，你的demo图片都比较正所以问题不大，如果长宽比比较大的图会出现，不过既然已经修复了，可能你自己已经发现问题了
