### ISSUE TITLE
华为&三星手机图片上传失败

### ISSUE THREAD

**Issue by rockliuxn** [think2011/localResizeIMG#45]
平台：微信6.3.5
设备：华为荣耀6 Plus PE-TL00  & 三星GALAXY A8
问题：图片上传失败

![Image of Yaktocat](http://dumpt.com/img/files/n4id0afwlhkfc5dyfvc0.jpg)

**Comment by think2011** [comment]
看起来是演示中无效的ajax请求的原因，再试试吧。

如果问题依旧，请截一下`UA：... `的内容。

**Comment by rockliuxn** [comment]
刚才又用华为P6调试了一下 http://think2011.github.io/localResizeIMG/test/ 的DEMO
发现 现在上传已经不进行 Ajax  Upload 上传请求了， 直接本地预览出来了
暂时看不到这个问题了
