### ISSUE TITLE
大神，请问压缩算法是什么

### ISSUE THREAD

**Issue by maya321** [think2011/localResizeIMG#46]
大神，请问压缩算法是什么

**Comment by think2011** [comment]
一般情况下是系统|浏览器自带的canvas里的jpeg算法，所以每台设备处理之后，文件的大小都有些偏差。

另外兼容android bug有一个额外jpeg算法，这个压缩的文件有些大，但总比没法压缩要好。
`src/lib/jpeg_encoder_basic.js`

**Comment by maya321** [comment]
嗯，谢谢，，能提供下lrz.all.bundle.js的源代码吗

**Comment by maya321** [comment]
git里面的代码我荡下来跑了，挺好的，谢谢分享，希望提供lrz.all.bundle.js没有经过压缩的，我研究下

**Comment by think2011** [comment]
源代码就在 `src/`文件夹里

-- 
think2011
Sent with Airmail

在 2015年11月12日 下午1:07:06, maya321 (notifications@github.com) 写到:

git里面的代码我荡下来跑了，挺好的，谢谢分享，希望提供lrz.all.bundle.js没有经过压缩的，我研究下

**Comment by maya321** [comment]
找到了，不用回复
