### ISSUE TITLE
图片一旦被压缩过后，后台获取不到文件类型啊？

### ISSUE THREAD

**Issue by lengxiaotian** [think2011/localResizeIMG#49]
图片没被压缩是正常的，压缩后我发现我这里图片文件类型获取不到；
在提交的数据中发现 filename="blob"
具体如下：
Content-Disposition: form-data; name="file"; filename="blob"
Content-Type: image/jpeg

这是为什么呢？？

**Comment by think2011** [comment]
如果你需要判断原始文件的类型，有个origin字段可以获得。   

压缩用的是JPEG算法，所以通通都是jpg类型。

发自我的 iPhone

**Comment by think2011** [comment]
噢，或许你是需要后端校验，我对这方面没有什么经验，或许你可以断点调试一下，接收到的formData里面的有什么可以用于校验的。

**Comment by lengxiaotian** [comment]
如果我上传的是png的图，宽度和高度都没有查过最大限制，这样的话后台获取到的还是png的格式；提交给后台的数据也不一样

![Uploading 360截图20151113101050329.jpg…]()
![Uploading 360截图20151113101124812.jpg…]()

**Comment by think2011** [comment]
抱歉，没看明白你说的，总之无论宽高经过处理之后，都会是jpeg格式的。（只有一种情况会发送源文件，当发现压缩后文件大小比源文件大的时候就会发源文件）

**Comment by jcs12311** [comment]
filename="blob"的问题是，经过处理之后，有一些文件的filename会被修改为blob，blob这个名字没有后缀，后端处理的时候就会报错说不支持该后缀，希望能修复一下，不要把filename修改为blob这个名字。。。

**Comment by jcs12311** [comment]
formData.append(that.defaults.fieldName, file);这一句，是有第三个参数的，把filename加在第三个参数.
formData.append(that.defaults.fieldName, file, that.file.name);就修复了后台无法识别后缀的问题了，但我不知道会不会带来其他影响

**Comment by think2011** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/FormData/append

>
filename Optional
The filename reported to the server (a USVString), when a Blob or File is passed as the second parameter. The default filename for Blob objects is "blob".

恩，可以的，方便的话，提个PR上来吧

**Comment by think2011** [comment]
@jcs12311 稍后我提交一下吧，刚好处理另外一个问题

**Comment by jcs12311** [comment]
好的，非常感谢！

**Comment by lengxiaotian** [comment]
@jcs12311 确实，说的真全面，我上不了图，所以一直没给讲明白！
@think2011 什么时候更新下这个BUG，^_^

**Comment by think2011** [comment]
@jcs12311 刚刚发布了最新的版本

**Comment by xifat** [comment]
下载的最新版，怎么解决这个问题呢？现在卡这个问题

**Comment by xifat** [comment]
@think2011

**Comment by lzj500** [comment]
@xifat 
用  formData.append('file', rst.file,rst.origin.name);这个方式就可以了。
