### ISSUE TITLE
rst.formData获取到的值为空，rst.fileLen也是为空

### ISSUE THREAD

**Issue by jcs12311** [think2011/localResizeIMG#50]
···
lrz(this.files[0])
        .then(function (rst) {
            // 处理成功会执行
            console.log(rst.origin, rst.formData);
        })
        .catch(function (err) {
            // 处理失败会执行
        })
        .always(function () {
            // 不管是成功失败，都会执行
        });
···

**Comment by think2011** [comment]
请提供更详细一些的信息，因为在线demo是可以的。

**Comment by jcs12311** [comment]
平台：windows7
设备：chrome 版本 45.0.2454.85

**Comment by jcs12311** [comment]
麻烦一下，以后能否在dist目录下提供完整的代码，比如lrz.all.bundle.js就显示完整源码,lrz.all.bundle.min.js才是压缩代码

**Comment by think2011** [comment]
1. 是用在线demo测试的吗？

2. 因为是用webpack打包的，所以即使提供未压缩的版本也是没有多大用处的，可以打开chrome控制台，会自动加载对应的.map文件，就能线上调试对应的源代码了。  具体可以搜索一下关键字 【压缩、合并、map】
![8084cc0c-1943-454a-ae3c-fa37c3901b2f](https://cloud.githubusercontent.com/assets/3961388/11136843/4521be18-89ed-11e5-8c14-14bdc716a26c.png)

**Comment by jcs12311** [comment]
感谢，已通过引用最新的lrz.all.bundle.js解决问题，我之前引用的版本是十几天前的。
