### ISSUE TITLE
上传图片问题

### ISSUE THREAD

**Issue by jcs12311** [think2011/localResizeIMG#51]
使用下面的文件上传，出现两个问题。
1.不指定宽度的话，图片转换出来的base64图片，宽度少了近一半，高度也是。

**Comment by think2011** [comment]
用的是某手机吗？

我在在线DEMO，用PC上传这张图片和对应的参数设置，都没能重现问题。

**Comment by jcs12311** [comment]
@think2011  图片失真应该是我处理的问题，不过我用在线demo试了那个宽度的问题，如果不制定宽度，出来的base64图片宽度会缩减一半

**Comment by think2011** [comment]
我用的是 MAC OS X，chrome46。

不指定宽高参数，用你之前发的图片，并没有重新问题，具体描述一下你的平台和浏览器吧。

**Comment by jcs12311** [comment]
我是win7, chrome
![default](https://cloud.githubusercontent.com/assets/7412060/11140961/4db774a4-8a1b-11e5-9152-e27795fd68b8.jpg)

**Comment by think2011** [comment]
@jcs12311 噢噢，我明白了。

看这里吧 https://github.com/think2011/localResizeIMG/blob/master/src/lrz.js#L304-L308

**Comment by shizhongyu** [comment]
![_20170112122145](https://cloud.githubusercontent.com/assets/13025541/21876866/b40502ee-d8c1-11e6-8f88-e219bb9c9f06.png)
