### ISSUE TITLE
发现rst.fileLen的值和实际服务器中保存的图片大小不一致？

### ISSUE THREAD

**Issue by lengxiaotian** [think2011/localResizeIMG#52]
上传成功了，在上传文件大一些，网速慢的时候后台会保存不完整；
想做一个验证文件是否完整，
发现就算上传成功，rst.fileLen的值比上传到服务器上的文件值大好多；

服务器端用两种保存图片的模式（rst.formData和rst.base64）保存的图片都一样大小，就是比前端传过来的rst.fileLen值小很多；

**Comment by think2011** [comment]
@lengxiaotian 

0. 确实会有网络不稳定导致上传不完整的情况，采用了formData的上传方式应该是相对稳定的。
1. 测试发现fileLen的大小是错误的，其实是base64的大小。
2. base64的话，其实就是发送base64字符串，后端接收的会跟base64.length一致的，除非出错了。

更新了版本。
