### ISSUE TITLE
微信上上传给后台的图片大小不对

### ISSUE THREAD

**Issue by jcs12311** [think2011/localResizeIMG#53]
在微信上，dataURItoBlob转换出来的blob对象大小太小。
我参照https://xts.so/demo/compress/index.html 上的代码，在
https://github.com/think2011/localResizeIMG/blob/master/src/lrz.js#L357
这一行，改为
```
return new BlobFormDataShim.Blob([ia.buffer], {type: mimeString});
```
就没问题了。

**Comment by think2011** [comment]
咦，那是什么原因呢？

**Comment by jcs12311** [comment]
Uint8Array.prototype.buffer 只读
Returns the ArrayBuffer referenced by the Uint8Array Fixed at construction time and thus read only.
可能需要接收的还是ArrayBuffer吧？

**Comment by think2011** [comment]
我不太明白，总之能够解决问题就好了，稍后更新一下，谢谢！

**Comment by jcs12311** [comment]
我也不清楚了啊，你写了BlobFormDataShim，我不知道会不会影响到之前正常的代码的，不清楚的话还是不建议更新吧

**Comment by think2011** [comment]
BlobFormDataShim里的代码也是来 https://xts.so/demo/compress/index.html，我检查一下，没问题的话，再更新。

**Comment by think2011** [comment]
> 微信上上传给后台的图片大小不对
> 在微信上，dataURItoBlob转换出来的blob对象大小太小。

我理解的是问题是在微信上图片文件上传的太小，所以保存不完整，是吗？

**Comment by jcs12311** [comment]
是根本出不来图片，是灰色的一块东西

**Comment by think2011** [comment]
用android 4.3（虚拟机）和iphone5 微信测试过，看起来没问题。
