### ISSUE TITLE
坚果上微信操作 压缩返回的formdata传不到服务器端

### ISSUE THREAD

**Issue by SevenBoy2012** [think2011/localResizeIMG#54]
平台：微信（6.3.7版）
设备：坚果（安卓4.4.4）
问题：压缩获取的formdata，发送给服务器端，接受不到文件。在pc端用chrome、火狐和QQ浏览器都可以。

**Comment by think2011** [comment]
今天刚好升级了个类似问题，看看现在用的lrz，是不是最新的版本？

**Comment by SevenBoy2012** [comment]
恩恩  不是最新版本的 我是上周的版本 稍后更新看看

**Comment by think2011** [comment]
在这里 #53，请顺便验证一下是否对其他环境有影响。

**Comment by SevenBoy2012** [comment]
恩恩  我后面会拿各种机型来测试  到时候再反馈

**Comment by SevenBoy2012** [comment]
还是不行。保存下来的图片。打不开的。

**Comment by think2011** [comment]
仅在微信下会有这样的问题吗？ 

另外记得微信缓存严重，需要强制清除缓存才能生效新的代码。

总之晚点找个时间试一下。

**Comment by SevenBoy2012** [comment]
卸载重装微信后可以保存  可是保存下来是没有后缀的一个文件。随便改了个图片后缀  是可以看的。问题是当第二次上传图片的时候。就又是损坏的图片了。

**Comment by think2011** [comment]
@SevenBoy2012 

http://think2011.github.io/localResizeIMG/test/

我给demo加上了基于`node.js`的后端处理，用对应的设备直接访问试试吧。

**Comment by SevenBoy2012** [comment]
![20151114014546951img_20151113_102021](https://cloud.githubusercontent.com/assets/2778925/11205599/eb03a770-8d43-11e5-97b7-3f9440b66ba1.jpg)

**Comment by SevenBoy2012** [comment]
![1037395115](https://cloud.githubusercontent.com/assets/2778925/11205702/bf837872-8d44-11e5-968b-eadbf8d0853b.jpg)

**Comment by SevenBoy2012** [comment]
手机上操作这个提示  是在微信上才这样

**Comment by jcs12311** [comment]
https://github.com/think2011/localResizeIMG/blob/master/src/lib/Blob.FormData.shim.js#L52
我之前好像也遇到这个问题，服务器返回错误是无法识别的文件，然后我在标示的这一行，加了一个"\r\n", value.type + '\r\n\r\n');就解决了，
不知道是否同一个问题，还有'\r\n'这个不知道在不同的系统会不会存在兼容性问题？

**Comment by think2011** [comment]
@jcs12311 晚点试试，目前已知在某些android4.0+，会发生这样的错误。

**Comment by think2011** [comment]
@jcs12311 
根据你的思路发现https://github.com/think2011/localResizeIMG/blob/2dafb24133cc7833a22e861245f6b1e4209a6476/src/lib/Blob.FormData.shim.js#L70
也需要加上 `\r\n`，问题就解决了。

@SevenBoy2012 在我这边测试通过了，更新版本后再试试吧！

**Comment by jcs12311** [comment]
我觉得这个问题很奇怪，也不知道是什么原因，所以没有提交issue，没想到真有这个问题。。。。 不懂@think2011

**Comment by SevenBoy2012** [comment]
@jcs12311 哈哈 bug就是这样的   没有一点点防备  没有一丝顾虑 就这样出现 
![image](https://cloud.githubusercontent.com/assets/2778925/11229838/b0342c1e-8dd4-11e5-95b5-6c41369e2613.png)
