### ISSUE TITLE
某些图片报错 Uncaught #<ProgressEvent>

### ISSUE THREAD

**Issue by jcs12311** [think2011/localResizeIMG#55]
平台：安卓微信。
用在线demo测试，上传到服务器，报错
图片：

![qq 20151118095733](https://cloud.githubusercontent.com/assets/7412060/11230651/73c93164-8ddb-11e5-8c1f-b24f2af5ba53.jpg)

**Comment by think2011** [comment]
跟这个的 #45 的问题一样，看起来是ajax的兼容性问题。

上面的图片测试我无法重现，可能得原件才行，希望能找到具体的问题特征。

**Comment by jcs12311** [comment]
http://pan.baidu.com/s/1pJL6Mh1
这个是原图，麻烦看看@think2011， 用带服务器的demo试试

**Comment by think2011** [comment]
还是没能重现（android4.3），不过我还是更新了一下，可以先去试一下。

**Comment by think2011** [comment]
猜测有可能不支持这个特性。

**Comment by jcs12311** [comment]
我修复了这个问题了。
原因是这个地方：
https://github.com/think2011/localResizeIMG/blob/master/src/lrz.js#L87
压缩文件太大就采用源文件，我上面那张图就是压缩之后比源文件大的那种，所以file给由blob替换为file了。
然后用了formDataShim的append：
https://github.com/think2011/localResizeIMG/blob/master/src/lib/Blob.FormData.shim.js#L55
把file添加进了parts.
最后，parts传进了BlobConstructor
https://github.com/think2011/localResizeIMG/blob/master/src/lib/Blob.FormData.shim.js#L72
然而BlobConstructor并不支持append file类型，只支持append blob类型。

参考：https://developer.mozilla.org/zh-CN/docs/Web/API/BlobBuilder

**Comment by jcs12311** [comment]
// Android上的AppleWebKit 534以前的内核存在一个Bug，
  // 导致FormData加入一个Blob对象后，上传的文件是0字节
所以才用了formdatashim，所以如果采用了源文件，不用formdatashim了

**Comment by think2011** [comment]
@jcs12311 赞！ 稍后我处理一下，顺便把shim改成按需加载。
