### ISSUE TITLE
循环上传的问题

### ISSUE THREAD

**Issue by devilmengcry** [think2011/localResizeIMG#56]
document.querySelector('input').addEventListener('change', function() {
    var that = this;

    for (var i = 0; i < that.files.length - 1; i++) {
        lrz(that.files[i], {
                width: 800
            })
            .then(function(rst) {
            });
    }
});
这样会漏掉最后一张选择的图片。

document.querySelector('input').addEventListener('change', function() {
    var that = this;

    for (var i = 0; i <= that.files.length - 1; i++) {
        lrz(that.files[i], {
                width: 800
            })
            .then(function(rst) {
            });
    }
});
这样一张都传不上。

**Comment by think2011** [comment]
我用在线demo测试一下，没法重现你的问题。

或许你输出一下`i`，看看每次的`i`是多少。

另外推荐这样的写法，会简洁很多。

```js
    [].forEach.call(this.files, function (v) {
        // lrz(v)....
    });
```

**Comment by devilmengcry** [comment]
[].forEach.call(this.files, function (v) {
    // lrz(v)....
});
这样子就没问题了，谢谢。
