### ISSUE TITLE
不能预览图片

### ISSUE THREAD

**Issue by zwl1619** [think2011/localResizeIMG#59]
这样写的代码，但不能预览图片，怎么的？
1、引入js
`<script src="/js/dist/lrz.bundle.js"></script>`
2、view
```<div id="upload-container" class="col-xs-12 text-center">
   <input onchange="upload().bind(this)" type="file" accept="image/*" />
</div>```
3、script
```
function upload () {
    lrz(this.files[0])
        .then(function (rst) {
        var img = new Image(),
            div = document.createElement('div'),
            p = document.createElement('p'),
            sourceSize = toFixed2(that.files[0].size / 1024),
            resultSize = toFixed2(rst.fileLen / 1024),
            scale = parseInt(100 - (resultSize / sourceSize * 100));

        p.style.fontSize = 13 + 'px';
        p.innerHTML      = '源文件：<span class="text-danger">' +
            sourceSize + 'KB' +
            '</span> <br />' +
            '压缩后传输大小：<span class="text-success">' +
            resultSize + 'KB (省' + scale + '%)' +
            '</span> ';

        div.className = 'col-sm-6';
        div.appendChild(img);
        div.appendChild(p);

        img.onload = function () {
            document.querySelector('#upload-container').appendChild(div);
        };

        img.src = rst.base64;
        return rst;
    })
        .catch(function (err) {
           alert(err);
        })
        .always(function () {
            
        });
}
```

**Comment by think2011** [comment]
目测没触发onload，可以把src赋值放到onlaod后面试试。

发自我的 iPhone

**Comment by zwl1619** [comment]
改成了上面的代码，仍然不能用

**Comment by think2011** [comment]
@zwl1619 写个demo吧，帮你debug看看。

**Comment by zwl1619** [comment]
复制了一下示例的代码，这样的：
视图：
<div id="upload-container" class="col-xs-12 text-center"> <input onchange="upload().bind(this)" type="file" accept="image/*" /> </div>
js代码：

function upload () {
    lrz(this.files[0])
        .then(function (rst) {
        var img = new Image(),
            div = document.createElement('div'),
            p = document.createElement('p'),
            sourceSize = toFixed2(that.files[0].size / 1024),
            resultSize = toFixed2(rst.fileLen / 1024),
            scale = parseInt(100 - (resultSize / sourceSize * 100));

        p.style.fontSize = 13 + 'px';
        p.innerHTML      = '源文件：<span class="text-danger">' +
            sourceSize + 'KB' +
            '</span> <br />' +
            '压缩后传输大小：<span class="text-success">' +
            resultSize + 'KB (省' + scale + '%)' +
            '</span> ';

        div.className = 'col-sm-6';
        div.appendChild(img);
        div.appendChild(p);

        img.onload = function () {
            document.querySelector('#upload-container').appendChild(div);
        };

        img.src = rst.base64;
        return rst;
    })
        .catch(function (err) {
           alert(err);
        })
        .always(function () {

        });
}

**Comment by think2011** [comment]
要不你打包一个Zip上来吧，这段代码看不出问题，也可以留意一下控制台输入有没有什么错误信息。

发自我的 iPhone

**Comment by think2011** [comment]
还有问题请重新开启
