### ISSUE TITLE
上传图片不能预览，附demo

### ISSUE THREAD

**Issue by zwl1619** [think2011/localResizeIMG#62]
[imguploadtest.txt](https://github.com/think2011/localResizeIMG/files/53225/imguploadtest.txt)
平台：windows 10
设备：pc
问题：上传图片不能预览。

备注：
1、上传zip格式的文件，提示不支持，所以改成了txt，改为zip即可。
2、js中有个 String.prototype.render = function (obj) 函数，可以删掉么？

***************
顺便问一下，readme中写到：
1、“没有jpeg压缩算法”：是指不能压缩jpg图片么？
2、“不支持new Blob,formData构造的文件size为0”，这个在什么使用场景会有问题？

**Comment by think2011** [comment]
@zwl1619 实在抱歉，发现示例代码写错了，已经更新了示例代码了。

可以根据示例的代码修改，按以下修改

```js
// 修改 <input onchange="upload().bind(this)" type="file" accept="image/*" />
<input onchange="upload.bind(this)()" type="file" accept="image/*" />
```
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Function/bind
