### ISSUE TITLE
有点需求改动，博主能否帮看看这个demo怎么修改一下？

### ISSUE THREAD

**Issue by zwl1619** [think2011/localResizeIMG#63]
[imguploadtest2.txt](https://github.com/think2011/localResizeIMG/files/54180/imguploadtest2.txt)

一、插件原本功能：可同时上传多张图片，ajax上传。
二、修改为：只需一张一张图片上传，不必ajax上传，有个input，点击的时候普通上传。预览的时候只预览一张图片，如果重新选择图片，则后面选择的图片代替前面的图片。
三、附件demo遇到的问题：
1、预览的时候会多张图片预览。
2、上传的图片是未压缩的原图片，需上传压缩后的图片。
3、附件为txt，改为zip即可。

**Comment by think2011** [comment]
我提供一些思路吧：

1. lrz只是接收用户选择的file，处理完成后给出base64或者formData供上传，要实现一张一张上传，只需要去掉input的多选属性
2. 预览的操作是能够自己控制的，只设定一个img元素，每次预览都只修改这个img的src就不会重复了。
3. lrz处理过的base64和formData都是压缩的（如果发现压缩过后文件大于源文件才会使用源文件大小）

另外可以clone这个repo，在`/test`下的`index.html`和`index.js`里面的代码刚好就是实现了你说的，可以参考一下。
