### ISSUE TITLE
上传图片成功后 再次点击上传按钮 然后点击空白处取消 会报错

### ISSUE THREAD

**Issue by xiaoily520** [think2011/localResizeIMG#65]
上传图片成功后 再次点击上传按钮 然后点击空白处取消 会报错（没有收到图片，可能的解决方案：https://github.com/think2011/localResizeIMG/issues/7），再操作一次就不会报错了 

华为4c手机 安卓5.1 用apicloud 真机调试

**Comment by think2011** [comment]
Duplicate #7
