### ISSUE TITLE
多个图片一同上传的怎么处理？

### ISSUE THREAD

**Issue by liyatang** [think2011/localResizeIMG#98]
原先后台要求传多个图片的formData形式是
var formData = new FormData();
formData.append('pic', file1);
formData.append('pic', file2);
formData.append('pic', file3);

用了lrz之后不知道怎么处理了。因为
选多个文件， 进过压缩，然后会得到 [rst, rst, rst]。  
而rst中提供了formData，but 怎么构成出上面的formData呢？

想不出来好的办法，貌似没法做？

and 组件为啥不提供file文件，让业务来自己组装formData 就好啦？

**Comment by think2011** [comment]
因为 `formData` 也有挨千刀的兼容性问题..

另外 file 文件其实是有的，看看这里 https://github.com/think2011/localResizeIMG/wiki/2.-%E5%8F%82%E6%95%B0%E6%96%87%E6%A1%A3

**Comment by liyatang** [comment]
thanks ,btw 得到的是 Blob对象。 有点可惜，不是File对象。   
and 问题已经解决

**Comment by wzc0x0** [comment]
请问问题怎么解决的？
